name = "marcocondrache"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-03-25"
compatibility_flags = [ "nodejs_compat" ]

routes = [
  { pattern = "marcocondrache.com", custom_domain = true }
]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true