import { cn } from "@/lib/utils";
import { Footer } from "@/components/footer";
import { Navigation } from "@/components/navigation";
import { ThemeProvider } from "@/components/theme-provider";

import "@/styles/globals.css";

import type { Metadata } from "next";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(GeistSans.variable, GeistMono.variable)}>
      <body className="bg-stone-50 antialiased dark:bg-stone-950">
        <ThemeProvider attribute="class" enableSystem>
          <main className="container mx-auto max-w-[712px] px-4 py-10">
            <Navigation />

            {children}
          </main>

          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
