// This file is generated by Velite

import config from '../velite.config'

type Collections = typeof config.collections

export type Projects = Collections['projects']['schema']['_output']
export declare const projects: Projects[]

export type Posts = Collections['posts']['schema']['_output']
export declare const posts: Posts[]
